name: Containerize and Deploy with Podman

on:
  push:
    branches:
      - master

jobs:
  backend:
    name: Build and Push Backend Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get -y install podman

      - name: Build Backend Image
        run: |
          podman build -t ghcr.io/${{ github.repository }}/backend:latest -f Containerfile .

      - name: Push Backend Image to GHCR
        run: |
          echo ${{ secrets.GHCR_PAT }} | podman login ghcr.io -u ${{ github.actor }} --password-stdin
          podman push ghcr.io/${{ github.repository }}/backend:latest

  frontend:
    name: Build and Push Frontend Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get -y install podman

      - name: Navigate to Frontend Directory
        run: cd frontend

      - name: Build Frontend Image
        run: |
          podman build -t ghcr.io/${{ github.repository }}/frontend:latest -f frontend/Containerfile frontend

      - name: Push Frontend Image to GHCR
        run: |
          echo ${{ secrets.GHCR_PAT }} | podman login ghcr.io -u ${{ github.actor }} --password-stdin
          podman push ghcr.io/${{ github.repository }}/frontend:latest
